name: Java CI with Maven

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"
                  cache: maven

            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2

            - name: Build with Maven
              working-directory: final
              run: mvn -B clean package

            - name: Verify WAR file exists before upload
              working-directory: final
              run: ls -al target

            - name: Upload build artifact (WAR file)
              uses: actions/upload-artifact@v4
              with:
                  name: trelloServer
                  path: final/target/*.war # ✅ 업로드 경로 수정

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: trelloServer
                  path: final/target/ # ✅ 다운로드 경로 수정

            - name: Verify WAR file exists after download
              run: ls -al final/target/

            - name: Deploy to EC2
              run: |
                  echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
                  chmod 600 private_key.pem
                  scp -i private_key.pem -o StrictHostKeyChecking=no final/target/*.war ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/trelloServer.war
                  ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
                    sudo systemctl restart tomcat
                  EOF
                  rm -f private_key.pem
